Possibly fix the Onesync Spectate Issue Mentioned in Issue #137
qbcore-framework/qb-adminmenu pull request #171
Opened 2022-08-21 01:31 UTC by amantu-qbit

Added Requested Collision Before the TP. Should Stick the Spectate with eh person which nullifies the problem we face with one sync. And it might fix the issue mentioned in #137 . I don't have a player base to test. Would be nice if anyone could try and give me feedback.

2022-08-24 14:30 UTC, sinphoenix commented
I tested with one person. I will do another test today with more people to ensure it works.

2022-08-28 17:15 UTC, kokorog commented
dont work for me

2023-05-04 18:25 UTC, GodyFromDiscord commented
PR Outdated from main, will test soon.

2023-05-05 18:21 UTC, amantu-qbit commented
> Thank you, will test shortly and feedback to the team

Thank you. Did some changes without being tested would greatly appreciate it if can get feedback!

2023-05-05 19:01 UTC, GodyFromDiscord commented on locales/en.lua
> +        ["no_player"] = 'Player Doesn\'t exist in server anymore',
Just reviewing and testing in game at the moment, but for the sake of grammar, if you don't make making 'Doesn\'t' to 'doesn\'t'

2023-05-05 19:01 UTC, GodyFromDiscord commented on client/client.lua
> +    CopyToClipboard('coords2')
This all works fine and looks good to me

2023-05-05 19:01 UTC, GodyFromDiscord requested changes
Just testing the spectate function now but I have also requested a tiny grammar change

2023-05-05 19:03 UTC, GodyFromDiscord commented
Upon spectating the player you contiously fall through the ground and it does not spectate them, this happens at a distance only, but when within a close range of the player, the spectate works fine

2023-05-05 19:08 UTC, amantu-qbit commented
> Upon spectating the player you continuously fall through the ground and it does not spectate them, this happens at a distance only, but when within a close range of the player, the spectate works fine

Thank you for the info. May I know apprx distance?

2023-05-05 19:09 UTC, GodyFromDiscord commented
> > Upon spectating the player you continuously fall through the ground and it does not spectate them, this happens at a distance only, but when within a close range of the player, the spectate works fine
> 
> Thank you for the info. May I know apprx distance?

I will create a video, one moment

2023-05-05 19:13 UTC, GodyFromDiscord commented
https://medal.tv/games/gta-v/clips/17WykA4Rlw1_pH/d1337SMnVVKv?invite=cr-MSw3WTMsNjI2NTgyMSw

Video ^

2023-05-05 19:15 UTC, amantu-qbit commented
> https://medal.tv/games/gta-v/clips/17WykA4Rlw1_pH/d1337SMnVVKv?invite=cr-MSw3WTMsNjI2NTgyMSw
> 
> Video ^

Thanks for the vid. Appreciate it!

meanwhile Did an update can you try?

2023-05-05 19:20 UTC, GodyFromDiscord commented
> > https://medal.tv/games/gta-v/clips/17WykA4Rlw1_pH/d1337SMnVVKv?invite=cr-MSw3WTMsNjI2NTgyMSw
> > Video ^
> 
> Thanks for the vid. Appreciate it!
> 
> meanwhile Did an update can you try?

Still facing the same issue as before with the latest push made

2023-10-08 23:20 UTC, closed without merging