adding auto switch locale system
qbcore-framework/qb-adminmenu pull request #175
Opened 2022-09-10 06:15 UTC by buddizer

**Describe Pull request**
adding auto switch locale system

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

2022-09-12 08:35 UTC, tom-osborne requested changes

2022-09-12 08:35 UTC, tom-osborne commented on fxmanifest.lua
>      'locales/en.lua', -- Change to the language you want
Please remove the comment, there is no need for the user to change this anymore.

2022-09-13 22:58 UTC, D4isDAVID approved these changes
LGTM

2022-09-14 07:55 UTC, tom-osborne approved these changes

2022-09-14 07:55 UTC, merged