add pt-br language support
qbcore-framework/qb-adminmenu pull request #184
Opened 2022-11-04 21:00 UTC by ggfto

Add support for pt-br language.

Have you personally loaded this code into an updated qbcore project and checked all it's functionality? YES
Does your code fit the style guidelines? YES
Does your PR fit the contribution guidelines? YES

2023-05-04 18:19 UTC, GodyFromDiscord requested changes
There's a change I have requested, other than that the rest is okay.

2023-05-04 18:19 UTC, GodyFromDiscord commented on locales/pt-br.lua
> +        fallbackLang = Lang,
This line isn't needed just;

Lang = Locale:new({
    phrases = Translations,
    warnOnMissing = true
})

2023-05-10 15:00 UTC, ChristianBDev commented
@ggfto Please update the code to the requested changes so we can continue

2023-05-10 16:56 UTC, ggfto commented
@ChristianBDev @GodyFromDiscord changes done folks!

2023-08-17 01:19 UTC, closed without merging