Create de.lua
qbcore-framework/qb-adminmenu pull request #98
Opened 2022-01-20 11:06 UTC by Seraph1982

de.lua for adminmenu

2022-01-21 00:25 UTC, jay-fivem approved these changes
Approved

2022-02-02 23:47 UTC, Tomboru requested changes

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["names_deactivated"] = "Names deactiviert",
```suggestion
        ["names_deactivated"] = "Namen deaktiviert",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["changed_perm_failed"] = "suche eine Gruppe aus!",
```suggestion
        ["changed_perm_failed"] = "Wähle eine Gruppe aus!",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["blips_activated"] = "Blips activiert",
```suggestion
        ["blips_activated"] = "Blips aktiviert",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["names_activated"] = "Names activiert",
```suggestion
        ["names_activated"] = "Namen aktiviert",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["body_health"] = "Karrosierie Health:",
```suggestion
        ["body_health"] = "Body Health:",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["your_position"] = "zu deiner position",
```suggestion
        ["your_position"] = "Zu dir",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["give"] = "gib",
```suggestion
        ["give"] = "Geben",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["admin_menu"] = "Admin Menu",
```suggestion
        ["admin_menu"] = "Admin Menü",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["online_players"] = "Online Spieler",
```suggestion
        ["online_players"] = "Spieler online",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["weather_conditions"] = "Vorhandene Wetter Optionen",
```suggestion
        ["weather_conditions"] = "Wetter Optionen",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["kick"] = "kick",
```suggestion
        ["kick"] = "Kick",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["revive"] = "Revive",
```suggestion
        ["revive"] = "Wiederbeleben",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["fix_vehicle"] = "Fixe Fahrzeug",
```suggestion
        ["fix_vehicle"] = "Fahrzeug reparieren",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["freeze"] = "Friere",
```suggestion
        ["freeze"] = "Einfrieren",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["spectate"] = "beobachten",
```suggestion
        ["spectate"] = "Beobachten",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["bring"] = "Bringe",
```suggestion
        ["bring"] = "Herbringen",
```

2022-02-02 23:47 UTC, Tomboru commented on locales/de.lua
> +        ["revive_desc"] = "Revive dich selbst",
```suggestion
        ["revive_desc"] = "Wiederbelebe dich selbst",
```

2022-02-11 06:38 UTC, FjamZoo commented
Please update your PR with the suggested changes from Tomboru and this can be pulled.

2022-04-07 00:33 UTC, merged